### ISSUE TITLE
[Question] Best practice for ThemeService in multi-window application?

### ISSUE THREAD

**Issue by MPITech** [ghost1372/DevWinUI#10]
Hi,

When using the ThemeService, it must be initialized with the window as a parameter.  In a multi-window app, should a new ThemeService be created for each window and its settings set to the main application window's settings?  Or should the main window's ThemeService just call .Initialize() on the newly created window?

Also, what is the best method for applying changes to the settings (tint color, backdrop) to all open windows?  If the above answer is to create a separate TheemService for each window, should I just apply the settings to each window's ThemeService in a loop?

Thanks!

**Comment by ghost1372** [comment]
It is not good to create multiple instances of a class for each window.
You can get backdrop and ElementTheme from ThemeService and manually set it in window loaded/ctor method.
I am considering adding multi-window support to the ThemeService.
But this requires you to track the windows that are created.

For example:
```
Window newWindow = new Window();
WindowHelper.TrackWindow(newWindow);
```

The TrackWindow method adds the windows to a dictionary, and finally the ThemeService can access the windows and apply theme/backdrop...

**Comment by ghost1372** [comment]
Hi @MPITech 
i added Multi-Window support for ThemeService.
when you created a window, you have to use `TrackWindow `like this:

`WindowHelper.TrackWindow(myWindow);`
then ThemeService will use a foreach in a list and apply all backdrop/elementTheme/Tint,....

**Comment by MPITech** [comment]
Awesome, thanks.  I was already tracking windows so this will be easy to integrate.  Thanks again.
