### ISSUE TITLE
Donating some custom code for easy HTML-like formatting in TextBlocks and RickTextBlocks

### ISSUE THREAD

**Issue by MPITech** [ghost1372/DevWinUI#12]
Hi.  I would like to donate some code to you that I created (admittedly with some help from ChatGPT) if you'd like to use it as-is or maybe to create a custom control in DevWinUI, if you are interested.  No attribution needed.

I had a control in WinForms that allowed for HTML formatting in text labels.  When I started with WinUI, it was one of the things I missed most.  So I created two helper functions to allow easily populating TextBlocks and RichTextBlocks with HTML-formatted content.  It is a lot easier than the standard way of using formatting in WinUI, in my opinion.

![image](https://github.com/user-attachments/assets/ad8528bb-753b-43cc-889f-260bbcc0463e)

Code for that text above:

```
var s = "Test of <b>bold</b> <i>italic</i> <u>underline</u><br>larger <font size='20'>font</font>||<font color='00c600'>Forecolor</font> <font bgcolor='00c600'> Background </font>||<font colors='cb3d00,004500'> Both combined </font>||regular";
FormatTextBlock(s, MyRichTextBlock);

```
I have it set to be an extension method on strings so I can apply them by just specifying `s.FormatTextBlock(MyRichTextBlock)` too.

Description:
It formats a RichTextBlock (or TextBlock, minus the Background color feature) using HTML-like formatting codes.  Supported tags:  `br`, `b`, `u`, `i`, `font size='size'`, and pipe characters which are treated like br (new lines).  Also supports `font color='hexcolor'` and `font bgcolor='hexcolor'.`  To combine both foreground and background colors, use `font colors='hexforecolor,hexbackcolor'` (colors separated by a comma).

Would you like my code?  You probably could improve it also, I bet.

**Comment by ghost1372** [comment]
Hi @MPITech,

Thank you for sharing this! It sounds interesting.

The CommunityToolkit currently includes a control for rendering [Markdown](https://github.com/CommunityToolkit/Labs-Windows/pull/480), which might also support some HTML formatting (though I haven’t tested this myself).

If your code offers unique functionality or addresses a different use case, I’d be happy to take a closer look. Feel free to create a pull request (PR) with your implementation so we can evaluate it and discuss how it might fit into the DevWinUI.

Thanks again for your contribution and for thinking of ways to enhance DevWinUI.

**Comment by MPITech** [comment]
Hi, I emailed you the code.  The Markdown control doesn't support HTML from that I saw in the demo project which is why I created this.  I prefer HTML but that's me.  If you'd like to create some sort of simple HTML-capable control label, that would be cool, up to you.  Use the code however you feel appropriate, or not at all.  :)

**Comment by MPITech** [comment]
One way I use this is in ContentDialog boxes presented to our users to bold certain dynamic text elements and also to create text blocks easily with colored backgrounds for highlighting text elements in the ContentDialogs and in our application.  For example, when a job price changes, the price difference is shown to the user with either a green background/black foreground amount for a raise in price of a red background/white foreground amount for a lower price.  This makes it easy to add in my ContentDialog creation code rather than trying to create different spans of formatted text.

**Comment by MPITech** [comment]
Cool!  Looking forward to seeing it.  Thanks.
