### ISSUE TITLE
FlipSlide Bug

### ISSUE THREAD

**Issue by Petrarca181** [ghost1372/DevWinUI#15]
If FlipSlide is loaded with  `IsFlipped = True `there is an exception. 

![image](https://github.com/user-attachments/assets/e3fcf04c-8a15-4ea8-be13-798023daf6b9)

**Comment by ghost1372** [comment]
Thank you, I will check and if there is a problem, I will fix it soon.

**Comment by ghost1372** [comment]
Fixed in https://github.com/ghost1372/DevWinUI/issues/15
