### ISSUE TITLE
FilePicker

### ISSUE THREAD

**Issue by Petrarca181** [ghost1372/DevWinUI#18]
Any way run filepicker with this scenario? ` *.* | All `?

ps. What magic did you used? How it runs with elevated app?

**Comment by ghost1372** [comment]
Hi @Petrarca181 
WinUI Picker is a little different than WPF

> [!CAUTION]
> for **FolderPicker** you should set a * symbol. Otherwise, Picker will not be executed.

`folderPicker.FileTypeFilter.Add("*");`

for **FileOpenPicker** we should use a 
`IList<string> fileTypeFilter`
which we can only specify file extension 

```
filePicker.FileTypeFilter.Add(".txt");
filePicker.FileTypeFilter.Add(".pdf");
```

> [!WARNING]  
> You cannot specify names for extensions. like Text Files | *.txt

> [!TIP]
> Also, by default, the **All Files** option will be displayed, which will only filter the specified extensions. if selected, only txt and pdf file will be shown.

> [!IMPORTANT]  
> if you want to show all files you should add a * without a dot . now your **All Files** option will filter all extensions.

```
filePicker.FileTypeFilter.Add("*");
```


for **FileSavePicker** we should use a 
```
IDictionary<string, IList<string>> fileTypeChoices
```
here we can define a name for extension.
```
picker.FileTypeChoices.Add("Csv", new List<string>() { ".csv" });
picker.FileTypeChoices.Add("Plain Text", new List<string>() { ".txt" });
```

> [!CAUTION]
> here we can not use * and if you try it you will get a exception and error message which **This file picker does not allow the all files extension.**


Does it work in elevated mode? I didn't know! 😅 In package or UnPackage mode? Let me test it too.
As far as I know it shouldn't work and a new Picker/API for WinUI work has started by MS on WASDK repo and will be available in wasdk v1.8+

**Comment by ghost1372** [comment]
Ok, i tested in elevated mode in Packaged and UnPackaged and Picker not working as expected. can you share more info you this is working for your in elevated mode?
Package.appxmanifest file:
```
<Capabilities>
  <rescap:Capability Name="runFullTrust" />
<rescap:Capability Name="allowElevation" />
</Capabilities>
```

app.Manifest

```
<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
	<security>
		<requestedPrivileges>
			<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
		</requestedPrivileges>
	</security>
</trustInfo>
```

and a method for check to see if we are elevated or not:
```

public static bool IsAdmin()
{
    var identity = WindowsIdentity.GetCurrent();
    var principal = new WindowsPrincipal(identity);
    return principal.IsInRole(WindowsBuiltInRole.Administrator);
}
```

i am on Windows 11 24H2.

**Comment by ghost1372** [comment]
> > Ok, i tested in elevated mode in Packaged and UnPackaged and Picker not working as expected. can you share more info, about how this is working for your in elevated mode? Package.appxmanifest file:
> > ```
> > <Capabilities>
> >   <rescap:Capability Name="runFullTrust" />
> > <rescap:Capability Name="allowElevation" />
> > </Capabilities>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > app.Manifest
> > ```
> > <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
> > 	<security>
> > 		<requestedPrivileges>
> > 			<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
> > 		</requestedPrivileges>
> > 	</security>
> > </trustInfo>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and a method for check to see if we are elevated or not:
> > ```
> > 
> > public static bool IsAdmin()
> > {
> >     var identity = WindowsIdentity.GetCurrent();
> >     var principal = new WindowsPrincipal(identity);
> >     return principal.IsInRole(WindowsBuiltInRole.Administrator);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i am on Windows 11 24H2.
> 
> ```
> var hasPrivilegedRights = Environment.IsPrivilegedProcess;
> 
> var identity = WindowsIdentity.GetCurrent();
> var principal = new WindowsPrincipal(identity);
> var hasPrivilegedRights2 = principal.IsInRole(WindowsBuiltInRole.Administrator);
> ```
> 
> both return true. drag&drop is locked as expected but filepicker works. 24H2 my system is broken? on 24h1 it was getting COM exception.

It's probably because of Windows, I get a COM exception on 24H2. 

current solution for elevated app is using Picker library which is using win32 apis.
https://github.com/[PavlikBender/Pickers](https://github.com/PavlikBender/Pickers)
