### ISSUE TITLE
[Suggestion] A NumberBox that binds directly to decimal values and not double

### ISSUE THREAD

**Issue by MPITech** [ghost1372/DevWinUI#19]
Hi.  I posted this issue in the 1.7 SDK Plans thread:
https://github.com/microsoft/WindowsAppSDK/discussions/4710#discussioncomment-11365351

You seem like the type of person smart enough to figure out a way to address this problem, but we have a major issue with NumberBoxes not binding directly to decimal values (only double).  When working with currency values stored in databases, you use decimal because double can cause rounding issues.  I don't understand why this isn't a bigger issue for more devs up to this point yet, but the only way to bind the NumberBoxes to decimal values is to use a converter, which seems like could cause the same rounding issues eventually.

I asked SyncFusion to address this and they said that their number box controls are based on the SDK ones so they can only support decimal when SDK does.  Do you think you can address this somehow in DevWinUI?

Thanks for listening/reading!  :)

**Comment by ghost1372** [comment]
@MPITech Yes, I am aware of this issue and unfortunately I don't have a solution in mind, the only option is to create a new control.
This problem needs to be solved by Microsoft and as you mentioned, the converter is a solution.
I voted for your comment.
 I hope Microsoft fixes this issue soon.
