### ISSUE TITLE
Will your HandyControls' DateTimePicker be migrated over?

### ISSUE THREAD

**Issue by AlexanderBlackman** [ghost1372/DevWinUI#3]
It looks really good.
https://ghost1372.github.io/handycontrol/extend_controls/dateTimePicker/

**Comment by ghost1372** [comment]
Thank you for your suggestion.
Great idea!

**Comment by ghost1372** [comment]
@AlexanderBlackman  This is a short report on the status of the work.
This took longer than I thought. It looks simple, but inside it requires more work.😁
Created a CalendarWithClock control (mybe i change this name!) where the timepicker can be positioned in 4 different directions.
also i retemplated calendarview
![image](https://github.com/user-attachments/assets/d0513b91-1867-4b06-bb5e-2e9b07fffd0b)


and DateTimePicker control Which needs more work, some bindings are not working properly.

![image](https://github.com/user-attachments/assets/88cc4436-c088-46d1-b4bb-cf3ec941af1c)

And most likely the analog clock will not be available for now. I need to build an analog clock from scratch and it will take more work. I can work on it after I finish this if I have enough time.

**Comment by ghost1372** [comment]
@AlexanderBlackman  CalendarWithClock and DateTimePicker now Added. i need more time to create a analog clock. so currently works fine with TimePicker!

[](https://raw.githubusercontent.com/ghost1372/DevWinUI-Resources/refs/heads/main/DevWinUI-Docs/DateTimePicker.gif)
[](https://raw.githubusercontent.com/ghost1372/DevWinUI-Resources/refs/heads/main/DevWinUI-Docs/CalendarWithClock.gif)

**Comment by ghost1372** [comment]
@AlexanderBlackman DateTimePicker, CalendarWithClock and Clock controls Added!😁

![](https://raw.githubusercontent.com/ghost1372/DevWinUI-Resources/refs/heads/main/DevWinUI-Docs/Clock.gif)

![](https://raw.githubusercontent.com/ghost1372/DevWinUI-Resources/refs/heads/main/DevWinUI-Docs/CalendarWithClock.gif)

![](https://raw.githubusercontent.com/ghost1372/DevWinUI-Resources/refs/heads/main/DevWinUI-Docs/DateTimePicker.gif)

**Comment by AlexanderBlackman** [comment]
Excellent!!! Thank you very much!
