### ISSUE TITLE
When will the DevWinUI Template be released?

### ISSUE THREAD

**Issue by scx1125** [ghost1372/DevWinUI#4]
Thank you for your great project. When will the new version of the template be released?

**Comment by ghost1372** [comment]
> Thank you for your great project. When will the new version of the template be released?

Templates has been recently released as a preview.
you can download it form here
https://marketplace.visualstudio.com/items?itemName=MahdiHosseini.DevWinUITemplates

> [!WARNING]
> Since the Nuget packages are currently in preview, preview versions of the Nuget packages must be installed (This is done by default in the preview version.)
The stable version will be released with the release of the preview or stable version of WASDK.
