### ISSUE TITLE
Missed dependencies when creating project with wizard

### ISSUE THREAD

**Issue by aexra** [ghost1372/DevWinUI#7]
When creating app with wizard there are some dependency errors: 
- CS1061 ContentDialog does not have contain definition ShowAsyncQueue in `AppUpdateSettingViewModel.cs` (selected Update Settings in wizard pages section)
- CS1061 JsonNavigationService does not contain definition ConfigureTitleBar in `MainPage.cs`

Wizard not supported for prerelease version?

**Comment by ghost1372** [comment]
> When creating app with wizard there are some dependency errors: 
> - CS1061 ContentDialog does not have contain definition ShowAsyncQueue in `AppUpdateSettingViewModel.cs` (selected Update Settings in wizard pages section)
> - CS1061 JsonNavigationService does not contain definition ConfigureTitleBar in `MainPage.cs`
> 
> Wizard not supported for prerelease version?

Wizard is in preview, i removed ContentDialog Extension but it seems that i forget to update `ShowAsyncQueue` to `ShowAsync`

I will upload a new nuget package which contains  `ConfigureTitleBar` method.
I was a little busy, I forgot to upload.

**Comment by ghost1372** [comment]
i uploaded DevWinUI v8.0.0-Preview3 nuget packages and VSIX Template v11.0.3 and they will be available soon after a few minutes.
