### ISSUE TITLE
Gallery app update feature not working

### ISSUE THREAD

**Issue by MPITech** [ghost1372/DevWinUI#9]
Hi again.  I was just downloading preview 3 and went to go to try and update my Gallery app from the app itself and saw this error message:

![image](https://github.com/user-attachments/assets/01db4bb2-fc50-43b7-8886-f562cd26de64)

I've never updated the app via this method before.  Should it be working or is this a temporary problem?  Thanks!

**Comment by ghost1372** [comment]
Hi, the built-in updater is not working right now.
You can currently download the gallery from the Actions section.
https://github.com/ghost1372/DevWinUI#%EF%B8%8F-nightly-build

**Comment by ghost1372** [comment]
Fixed in https://github.com/ghost1372/DevWinUI/commit/3d0ac4569d33e4057021a2876c0133ffe1a7d708
